#!/usr/bin/env bash
# Fetch all vendor sources at their pinned SHAs and apply local patches.
# Idempotent: re-running with the same MANIFEST produces no changes.
#
# Output: sources/{u-boot-vendor,kernel,allwinner-bsp,allwinner-target,allwinner-device}
#         sources/MANIFEST.lock

set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

log "==> Stage 3: fetching vendor sources"

require_var ORANGEPI_BUILD_COMMIT
require_var KERNEL_COMMIT
require_var UBOOT_COMMIT
require_var BSP_COMMIT
require_var TARGET_COMMIT
require_var DEVICE_COMMIT
require_var AIC8800_COMMIT
require_var AI_SDK_COMMIT

fetch_pinned "$ORANGEPI_BUILD_REPO" "$ORANGEPI_BUILD_BRANCH" "$ORANGEPI_BUILD_COMMIT" "$SOURCES_DIR/orangepi-build"
fetch_pinned "$KERNEL_REPO"         "$KERNEL_BRANCH"         "$KERNEL_COMMIT"         "$SOURCES_DIR/kernel"
fetch_pinned "$UBOOT_REPO"          "$UBOOT_BRANCH"          "$UBOOT_COMMIT"          "$SOURCES_DIR/u-boot-vendor"
fetch_pinned "$BSP_REPO"            "$BSP_BRANCH"            "$BSP_COMMIT"            "$SOURCES_DIR/allwinner-bsp"
fetch_pinned "$TARGET_REPO"         "$TARGET_BRANCH"         "$TARGET_COMMIT"         "$SOURCES_DIR/allwinner-target"
fetch_pinned "$DEVICE_REPO"         "$DEVICE_BRANCH"         "$DEVICE_COMMIT"         "$SOURCES_DIR/allwinner-device"
fetch_pinned "$AIC8800_REPO"        "$AIC8800_BRANCH"        "$AIC8800_COMMIT"        "$SOURCES_DIR/aic8800"
fetch_pinned "$AI_SDK_REPO"         "$AI_SDK_BRANCH"         "$AI_SDK_COMMIT"         "$SOURCES_DIR/ai-sdk"

log "==> verifying orangepi-build defconfig"
# orangepi-build keeps its sun60iw2 defconfig at this path. Kernel and U-Boot
# patch series for sun60iw2 are NOT present in the current orangepi-build
# checkout (external/patch/ has only atf/ and misc/). The kernel build stage
# will apply only local patches from patches/kernel/.
ORANGEPI_DEFCONFIG="$SOURCES_DIR/orangepi-build/external/config/kernel/linux-sun60iw2-current-a733.config"

for p in "$ORANGEPI_DEFCONFIG"; do
  [[ -e "$p" ]] || warn "missing in orangepi-build checkout: $p (verify branch)"
done

log "==> applying local patches"
apply_patches "$SOURCES_DIR/u-boot-vendor" "$PATCHES_DIR/u-boot"
apply_patches "$SOURCES_DIR/kernel"        "$PATCHES_DIR/kernel"

# ---- Extract stock boot0 from Radxa image ----
log "==> extracting stock boot0 from Radxa image"
require_var RADXA_IMAGE_URL
require_var RADXA_IMAGE_SHA256
require_var BOOT0_SECTOR
require_var BOOT0_SIZE
require_var BOOT0_SHA256

RADXA_IMAGE="$SOURCES_DIR/$(basename "$RADXA_IMAGE_URL")"
BOOT0_FILE="$SOURCES_DIR/boot0_stock.bin"

if [[ -f "$BOOT0_FILE" ]]; then
  have_sha=$(sha256sum "$BOOT0_FILE" | cut -d' ' -f1)
  if [[ "$have_sha" == "$BOOT0_SHA256" ]]; then
    log "  boot0_stock.bin already extracted and verified"
  else
    warn "  boot0_stock.bin SHA256 mismatch ($have_sha), re-extracting"
    rm -f "$BOOT0_FILE"
  fi
fi

if [[ ! -f "$BOOT0_FILE" ]]; then
  # Download Radxa image if not cached
  if [[ ! -f "$RADXA_IMAGE" ]]; then
    log "  downloading $(basename "$RADXA_IMAGE_URL") (~1 GB)"
    wget -q --show-progress -O "$RADXA_IMAGE.tmp" "$RADXA_IMAGE_URL"
    mv "$RADXA_IMAGE.tmp" "$RADXA_IMAGE"
  fi

  # Verify image checksum
  img_sha=$(sha256sum "$RADXA_IMAGE" | cut -d' ' -f1)
  [[ "$img_sha" == "$RADXA_IMAGE_SHA256" ]] \
    || die "Radxa image SHA256 mismatch: expected $RADXA_IMAGE_SHA256, got $img_sha"

  # Extract boot0 from sector $BOOT0_SECTOR
  # xzcat exits with SIGPIPE (141) when dd closes early — that's expected.
  log "  extracting boot0 from sector $BOOT0_SECTOR ($BOOT0_SIZE bytes)"
  ( xzcat "$RADXA_IMAGE" || true ) \
    | dd bs=512 skip="$BOOT0_SECTOR" count=$(( BOOT0_SIZE / 512 )) iflag=fullblock status=none \
    > "$BOOT0_FILE.tmp"
  mv "$BOOT0_FILE.tmp" "$BOOT0_FILE"

  # Verify boot0 checksum
  b0_sha=$(sha256sum "$BOOT0_FILE" | cut -d' ' -f1)
  [[ "$b0_sha" == "$BOOT0_SHA256" ]] \
    || die "boot0 SHA256 mismatch: expected $BOOT0_SHA256, got $b0_sha"

  # Verify eGON magic
  magic=$(dd if="$BOOT0_FILE" bs=1 skip=4 count=8 status=none)
  [[ "$magic" == "eGON.BT0" ]] \
    || die "boot0 eGON magic not found (got '$magic')"

  log "  boot0_stock.bin OK: $BOOT0_SHA256"
fi

log "==> writing MANIFEST.lock"
{
  echo "# Auto-generated by 00-fetch-sources.sh. Commit this file."
  echo "# Generated: $(date -u +%FT%TZ)"
  for sub in orangepi-build kernel u-boot-vendor allwinner-bsp allwinner-target allwinner-device aic8800 ai-sdk; do
    printf '%-22s %s\n' "$sub" "$(git -C "$SOURCES_DIR/$sub" rev-parse HEAD)"
  done
} > "$SOURCES_DIR/MANIFEST.lock"

log "done. MANIFEST.lock:"
cat "$SOURCES_DIR/MANIFEST.lock" >&2
